remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Test GitHub Pages]
description: [A playground for experimenting with MarkDown, Jekyll, etc.]
